package es.cabsa.javadevelopers.controller;

public abstract class Constants {
    //JSON Hardcoded. It should be added to DB once parsed but requires some time to do so I skipped that part
    public static String jsonString = "{"
            + "  \"animal\": ["
            + "    {"
            + "      \"id\": \"0\","
            + "      \"name\": \"Rabbit\","
            + "      \"legs\": \"4\","
            + "      \"eats\": \"0\""
            + "    },"
            + "    {"
            + "      \"id\": \"1\","
            + "      \"name\": \"Bear\","
            + "      \"legs\": \"4\","
            + "      \"eats\": \"2\""
            + "    },"
            + "    {"
            + "      \"id\": \"2\","
            + "      \"name\": \"Deer\","
            + "      \"legs\": \"4\","
            + "      \"eats\": \"4\""
            + "    },"
            + "    {"
            + "      \"id\": \"3\","
            + "      \"name\": \"Snake\","
            + "      \"legs\": \"0\","
            + "      \"eats\": \"5\""
            + "    },"
            + "    {"
            + "      \"id\": \"4\","
            + "      \"name\": \"Coocodrile\","
            + "      \"legs\": \"4\","
            + "      \"eats\": \"3\""
            + "    },"
            + "    {"
            + "      \"id\": \"5\","
            + "      \"name\": \"Chicken\","
            + "      \"legs\": \"2\","
            + "      \"eats\": \"1\""
            + "    },"
            + "    {"
            + "      \"id\": \"6\","
            + "      \"name\": \"Spider\","
            + "      \"legs\": \"8\","
            + "      \"eats\": \"3\""
            + "    }"
            + "  ],"
            + "  \"food\": ["
            + "    {"
            + "      \"id\": \"0\","
            + "      \"name\": \"carrot\""
            + "    },"
            + "    {"
            + "      \"id\": \"1\","
            + "      \"name\": \"honey\""
            + "    },"
            + "    {"
            + "      \"id\": \"2\","
            + "      \"name\": \"leafs\""
            + "    },"
            + "    {"
            + "      \"id\": \"3\","
            + "      \"name\": \"insects\""
            + "    },"
            + "    {"
            + "      \"id\": \"4\","
            + "      \"name\": \"vermin\""
            + "    },"
            + "    {"
            + "      \"id\": \"5\","
            + "      \"name\": \"birdseed\""
            + "    }"
            + "  ]"
            + "}";
}
